QT += quick

CONFIG += c++11

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

HEADERS += \
        include/MadgwickAHRS.h \
        include/gpio_assign.h \
        include/localizedstring.h \
        include/logic.h \
        include/movement.h \
        include/proximity.h \
        include/qr.hpp \
        include/sensors.h \
        include/test.h \
        opencv-4.1.0/include/opencv4/opencv2/aruco.hpp \
        opencv-4.1.0/include/opencv4/opencv2/aruco/charuco.hpp \
        opencv-4.1.0/include/opencv4/opencv2/aruco/dictionary.hpp \
        opencv-4.1.0/include/opencv4/opencv2/bgsegm.hpp \
        opencv-4.1.0/include/opencv4/opencv2/bioinspired.hpp \
        opencv-4.1.0/include/opencv4/opencv2/bioinspired/bioinspired.hpp \
        opencv-4.1.0/include/opencv4/opencv2/bioinspired/retina.hpp \
        opencv-4.1.0/include/opencv4/opencv2/bioinspired/retinafasttonemapping.hpp \
        opencv-4.1.0/include/opencv4/opencv2/bioinspired/transientareassegmentationmodule.hpp \
        opencv-4.1.0/include/opencv4/opencv2/calib3d.hpp \
        opencv-4.1.0/include/opencv4/opencv2/calib3d/calib3d.hpp \
        opencv-4.1.0/include/opencv4/opencv2/calib3d/calib3d_c.h \
        opencv-4.1.0/include/opencv4/opencv2/ccalib.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ccalib/multicalib.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ccalib/omnidir.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ccalib/randpattern.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/affine.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/base.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/bindings_utils.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/bufferpool.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/check.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/core_c.h \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda.inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/block.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/border_interpolate.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/color.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/common.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/datamov_utils.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/detail/color_detail.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/detail/reduce.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/detail/reduce_key_val.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/detail/transform_detail.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/detail/type_traits_detail.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/detail/vec_distance_detail.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/dynamic_smem.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/emulation.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/filters.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/funcattrib.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/functional.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/limits.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/reduce.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/saturate_cast.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/scan.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/simd_functions.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/transform.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/type_traits.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/utility.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/vec_distance.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/vec_math.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/vec_traits.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/warp.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/warp_reduce.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda/warp_shuffle.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda_stream_accessor.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cuda_types.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
        opencv-4.1.0/include/opencv4/opencv2/core/cv_cpu_helper.h \
        opencv-4.1.0/include/opencv4/opencv2/core/cvdef.h \
        opencv-4.1.0/include/opencv4/opencv2/core/cvstd.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cvstd.inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/directx.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/eigen.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/fast_math.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/hal.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/interface.h \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin_avx.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin_cpp.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin_forward.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin_neon.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin_sse.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin_sse_em.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/hal/intrin_vsx.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/mat.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/mat.inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/matx.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/neon_utils.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/ocl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/ocl_genbase.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/ocl_defs.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/opencl_info.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/opencl_svm.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdblas.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdfft.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_gl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_20.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/opengl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/operations.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/optim.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/ovx.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/persistence.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/saturate.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/softfloat.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/sse_utils.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/traits.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/types.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/types_c.h \
        opencv-4.1.0/include/opencv4/opencv2/core/utility.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/utils/filesystem.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/utils/logger.defines.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/utils/logger.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/utils/trace.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/va_intel.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/version.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core/vsx_utils.hpp \
        opencv-4.1.0/include/opencv4/opencv2/core_detect.hpp \
        opencv-4.1.0/include/opencv4/opencv2/cvconfig.h \
        opencv-4.1.0/include/opencv4/opencv2/datasets/ar_hmdb.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/ar_sports.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/dataset.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/fr_adience.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/fr_lfw.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/gr_chalearn.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/gr_skig.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/hpe_humaneva.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/hpe_parse.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/ir_affine.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/ir_robot.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/is_bsds.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/is_weizmann.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/msm_epfl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/msm_middlebury.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/or_imagenet.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/or_mnist.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/or_pascal.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/or_sun.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/pd_caltech.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/pd_inria.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/slam_kitti.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/slam_tumindoor.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/tr_chars.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/tr_icdar.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/tr_svt.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/track_alov.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/track_vot.hpp \
        opencv-4.1.0/include/opencv4/opencv2/datasets/util.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/all_layers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/dict.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/dnn.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/dnn.inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/layer.details.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/layer.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/shape_utils.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dnn/version.hpp \
        opencv-4.1.0/include/opencv4/opencv2/dpm.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/bif.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/face_alignment.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/facemark.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/facemarkAAM.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/facemarkLBF.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/facemark_train.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/facerec.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/mace.hpp \
        opencv-4.1.0/include/opencv4/opencv2/face/predict_collector.hpp \
        opencv-4.1.0/include/opencv4/opencv2/features2d.hpp \
        opencv-4.1.0/include/opencv4/opencv2/features2d/features2d.hpp \
        opencv-4.1.0/include/opencv4/opencv2/features2d/hal/interface.h \
        opencv-4.1.0/include/opencv4/opencv2/flann.hpp \
        opencv-4.1.0/include/opencv4/opencv2/flann/all_indices.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/allocator.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/any.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/autotuned_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/composite_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/config.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/defines.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/dist.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/dummy.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/dynamic_bitset.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/flann.hpp \
        opencv-4.1.0/include/opencv4/opencv2/flann/flann_base.hpp \
        opencv-4.1.0/include/opencv4/opencv2/flann/general.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/ground_truth.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/heap.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/index_testing.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/kdtree_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/kdtree_single_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/kmeans_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/linear_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/logger.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/lsh_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/lsh_table.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/matrix.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/miniflann.hpp \
        opencv-4.1.0/include/opencv4/opencv2/flann/nn_index.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/object_factory.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/params.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/random.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/result_set.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/sampling.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/saving.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/simplex_downhill.h \
        opencv-4.1.0/include/opencv4/opencv2/flann/timer.h \
        opencv-4.1.0/include/opencv4/opencv2/freetype.hpp \
        opencv-4.1.0/include/opencv4/opencv2/fuzzy.hpp \
        opencv-4.1.0/include/opencv4/opencv2/fuzzy/fuzzy_F0_math.hpp \
        opencv-4.1.0/include/opencv4/opencv2/fuzzy/fuzzy_F1_math.hpp \
        opencv-4.1.0/include/opencv4/opencv2/fuzzy/fuzzy_image.hpp \
        opencv-4.1.0/include/opencv4/opencv2/fuzzy/types.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/cpu/core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/cpu/gcpukernel.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/cpu/imgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/fluid/core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/fluid/gfluidbuffer.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/fluid/gfluidkernel.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/fluid/imgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/garg.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/garray.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gcall.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gcommon.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gcompiled.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gcompoundkernel.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gcomputation.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gkernel.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gmat.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gmetaarg.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gproto.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gpu/core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gpu/ggpukernel.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gpu/imgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gscalar.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gtype_traits.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/gtyped.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/imgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/ocl/core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/ocl/goclkernel.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/ocl/imgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/opencv_includes.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/operators.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/assert.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/convert.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/cvdefs.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/exports.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/mat.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/saturate.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/scalar.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/own/types.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/util/any.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/util/compiler_hints.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/util/optional.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/util/throw.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/util/util.hpp \
        opencv-4.1.0/include/opencv4/opencv2/gapi/util/variant.hpp \
        opencv-4.1.0/include/opencv4/opencv2/hfs.hpp \
        opencv-4.1.0/include/opencv4/opencv2/highgui.hpp \
        opencv-4.1.0/include/opencv4/opencv2/highgui/highgui.hpp \
        opencv-4.1.0/include/opencv4/opencv2/highgui/highgui_c.h \
        opencv-4.1.0/include/opencv4/opencv2/img_hash.hpp \
        opencv-4.1.0/include/opencv4/opencv2/img_hash/average_hash.hpp \
        opencv-4.1.0/include/opencv4/opencv2/img_hash/block_mean_hash.hpp \
        opencv-4.1.0/include/opencv4/opencv2/img_hash/color_moment_hash.hpp \
        opencv-4.1.0/include/opencv4/opencv2/img_hash/img_hash_base.hpp \
        opencv-4.1.0/include/opencv4/opencv2/img_hash/marr_hildreth_hash.hpp \
        opencv-4.1.0/include/opencv4/opencv2/img_hash/phash.hpp \
        opencv-4.1.0/include/opencv4/opencv2/img_hash/radial_variance_hash.hpp \
        opencv-4.1.0/include/opencv4/opencv2/imgcodecs.hpp \
        opencv-4.1.0/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
        opencv-4.1.0/include/opencv4/opencv2/imgcodecs/imgcodecs_c.h \
        opencv-4.1.0/include/opencv4/opencv2/imgcodecs/ios.h \
        opencv-4.1.0/include/opencv4/opencv2/imgcodecs/legacy/constants_c.h \
        opencv-4.1.0/include/opencv4/opencv2/imgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/imgproc/detail/gcgraph.hpp \
        opencv-4.1.0/include/opencv4/opencv2/imgproc/hal/hal.hpp \
        opencv-4.1.0/include/opencv4/opencv2/imgproc/hal/interface.h \
        opencv-4.1.0/include/opencv4/opencv2/imgproc/imgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/imgproc/imgproc_c.h \
        opencv-4.1.0/include/opencv4/opencv2/imgproc/types_c.h \
        opencv-4.1.0/include/opencv4/opencv2/line_descriptor.hpp \
        opencv-4.1.0/include/opencv4/opencv2/line_descriptor/descriptor.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ml.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ml/ml.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ml/ml.inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/objdetect.hpp \
        opencv-4.1.0/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
        opencv-4.1.0/include/opencv4/opencv2/objdetect/objdetect.hpp \
        opencv-4.1.0/include/opencv4/opencv2/opencv.hpp \
        opencv-4.1.0/include/opencv4/opencv2/opencv_modules.hpp \
        opencv-4.1.0/include/opencv4/opencv2/optflow.hpp \
        opencv-4.1.0/include/opencv4/opencv2/optflow/motempl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/optflow/pcaflow.hpp \
        opencv-4.1.0/include/opencv4/opencv2/optflow/rlofflow.hpp \
        opencv-4.1.0/include/opencv4/opencv2/optflow/sparse_matching_gpc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/phase_unwrapping.hpp \
        opencv-4.1.0/include/opencv4/opencv2/phase_unwrapping/histogramphaseunwrapping.hpp \
        opencv-4.1.0/include/opencv4/opencv2/phase_unwrapping/phase_unwrapping.hpp \
        opencv-4.1.0/include/opencv4/opencv2/photo.hpp \
        opencv-4.1.0/include/opencv4/opencv2/photo/cuda.hpp \
        opencv-4.1.0/include/opencv4/opencv2/photo/legacy/constants_c.h \
        opencv-4.1.0/include/opencv4/opencv2/photo/photo.hpp \
        opencv-4.1.0/include/opencv4/opencv2/plot.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality/quality_utils.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality/qualitybase.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality/qualitybrisque.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality/qualitygmsd.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality/qualitymse.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality/qualitypsnr.hpp \
        opencv-4.1.0/include/opencv4/opencv2/quality/qualityssim.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/map.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mapaffine.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mapper.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mappergradaffine.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mappergradeuclid.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mappergradproj.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mappergradshift.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mappergradsimilar.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mapperpyramid.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mapprojec.hpp \
        opencv-4.1.0/include/opencv4/opencv2/reg/mapshift.hpp \
        opencv-4.1.0/include/opencv4/opencv2/rgbd.hpp \
        opencv-4.1.0/include/opencv4/opencv2/rgbd/depth.hpp \
        opencv-4.1.0/include/opencv4/opencv2/rgbd/kinfu.hpp \
        opencv-4.1.0/include/opencv4/opencv2/rgbd/linemod.hpp \
        opencv-4.1.0/include/opencv4/opencv2/saliency.hpp \
        opencv-4.1.0/include/opencv4/opencv2/saliency/saliencyBaseClasses.hpp \
        opencv-4.1.0/include/opencv4/opencv2/saliency/saliencySpecializedClasses.hpp \
        opencv-4.1.0/include/opencv4/opencv2/shape.hpp \
        opencv-4.1.0/include/opencv4/opencv2/shape/emdL1.hpp \
        opencv-4.1.0/include/opencv4/opencv2/shape/hist_cost.hpp \
        opencv-4.1.0/include/opencv4/opencv2/shape/shape.hpp \
        opencv-4.1.0/include/opencv4/opencv2/shape/shape_distance.hpp \
        opencv-4.1.0/include/opencv4/opencv2/shape/shape_transformer.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stereo.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stereo/descriptor.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stereo/matching.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stereo/quasi_dense_stereo.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stereo/stereo.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/autocalib.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/blenders.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/camera.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/matchers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/timelapsers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/util.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/warpers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/stitching/warpers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/structured_light.hpp \
        opencv-4.1.0/include/opencv4/opencv2/structured_light/graycodepattern.hpp \
        opencv-4.1.0/include/opencv4/opencv2/structured_light/sinusoidalpattern.hpp \
        opencv-4.1.0/include/opencv4/opencv2/structured_light/structured_light.hpp \
        opencv-4.1.0/include/opencv4/opencv2/superres.hpp \
        opencv-4.1.0/include/opencv4/opencv2/superres/optical_flow.hpp \
        opencv-4.1.0/include/opencv4/opencv2/surface_matching.hpp \
        opencv-4.1.0/include/opencv4/opencv2/surface_matching/icp.hpp \
        opencv-4.1.0/include/opencv4/opencv2/surface_matching/pose_3d.hpp \
        opencv-4.1.0/include/opencv4/opencv2/surface_matching/ppf_helpers.hpp \
        opencv-4.1.0/include/opencv4/opencv2/surface_matching/ppf_match_3d.hpp \
        opencv-4.1.0/include/opencv4/opencv2/surface_matching/t_hash_int.hpp \
        opencv-4.1.0/include/opencv4/opencv2/text.hpp \
        opencv-4.1.0/include/opencv4/opencv2/text/erfilter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/text/ocr.hpp \
        opencv-4.1.0/include/opencv4/opencv2/text/textDetector.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking/feature.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking/kalman_filters.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking/onlineBoosting.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking/onlineMIL.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking/tldDataset.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking/tracker.hpp \
        opencv-4.1.0/include/opencv4/opencv2/tracking/tracking.hpp \
        opencv-4.1.0/include/opencv4/opencv2/video.hpp \
        opencv-4.1.0/include/opencv4/opencv2/video/background_segm.hpp \
        opencv-4.1.0/include/opencv4/opencv2/video/legacy/constants_c.h \
        opencv-4.1.0/include/opencv4/opencv2/video/tracking.hpp \
        opencv-4.1.0/include/opencv4/opencv2/video/video.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videoio.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videoio/cap_ios.h \
        opencv-4.1.0/include/opencv4/opencv2/videoio/legacy/constants_c.h \
        opencv-4.1.0/include/opencv4/opencv2/videoio/registry.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videoio/videoio.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videoio/videoio_c.h \
        opencv-4.1.0/include/opencv4/opencv2/videostab.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/deblurring.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/fast_marching.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/fast_marching_inl.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/frame_source.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/global_motion.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/inpainting.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/log.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/motion_core.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/motion_stabilizing.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/optical_flow.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/outlier_rejection.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/ring_buffer.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/stabilizer.hpp \
        opencv-4.1.0/include/opencv4/opencv2/videostab/wobble_suppression.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xfeatures2d.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xfeatures2d/cuda.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xfeatures2d/nonfree.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/brightedges.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/color_match.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/deriche_filter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/disparity_filter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/edge_filter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/edgeboxes.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/edgepreserving_filter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/estimated_covariance.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/fast_hough_transform.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/fast_line_detector.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/fourier_descriptors.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/lsc.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/paillou_filter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/peilin.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/ridgefilter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/run_length_morphology.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/seeds.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/segmentation.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/slic.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/sparse_match_interpolator.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/structured_edge_detection.hpp \
        opencv-4.1.0/include/opencv4/opencv2/ximgproc/weighted_median_filter.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xobjdetect.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xphoto.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xphoto/bm3d_image_denoising.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xphoto/dct_image_denoising.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xphoto/inpainting.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xphoto/oilpainting.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xphoto/tonemap.hpp \
        opencv-4.1.0/include/opencv4/opencv2/xphoto/white_balance.hpp \
        test.h

SOURCES += \
        src/MadgwickAHRS.c \
        src/imu.c \
        src/localizedstring.cpp \
        src/logic.cpp \
        src/main.cpp \
        src/movement.c \
        src/proximity.cpp \
        src/qr_module.cpp \
        src/test.cpp \

RESOURCES += qml.qrc

TRANSLATIONS += \
    other/GUI_en_GB.ts

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

INCLUDEPATH += include

DISTFILES += \
    .gitignore \
    COPYING \
    README.md \
    bin/delete.me \
    build/MadgwickAHRS.d \
    build/imu.d \
    build/logic.d \
    build/main.d \
    build/movement.d \
    build/proximity.d \
    build/qr_module.d \
    doc/delete.me \
    lib/delete.me \
    opencv-4.1.0/bin/opencv_annotation \
    opencv-4.1.0/bin/opencv_interactive-calibration \
    opencv-4.1.0/bin/opencv_version \
    opencv-4.1.0/bin/opencv_visualisation \
    opencv-4.1.0/bin/opencv_waldboost_detector \
    opencv-4.1.0/bin/setup_vars_opencv4.sh \
    opencv-4.1.0/lib/cmake/opencv4/OpenCVConfig-version.cmake \
    opencv-4.1.0/lib/cmake/opencv4/OpenCVConfig.cmake \
    opencv-4.1.0/lib/cmake/opencv4/OpenCVModules-release.cmake \
    opencv-4.1.0/lib/cmake/opencv4/OpenCVModules.cmake \
    opencv-4.1.0/lib/libopencv_aruco.so \
    opencv-4.1.0/lib/libopencv_aruco.so.4.1 \
    opencv-4.1.0/lib/libopencv_aruco.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_bgsegm.so \
    opencv-4.1.0/lib/libopencv_bgsegm.so.4.1 \
    opencv-4.1.0/lib/libopencv_bgsegm.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_bioinspired.so \
    opencv-4.1.0/lib/libopencv_bioinspired.so.4.1 \
    opencv-4.1.0/lib/libopencv_bioinspired.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_calib3d.so \
    opencv-4.1.0/lib/libopencv_calib3d.so.4.1 \
    opencv-4.1.0/lib/libopencv_calib3d.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_ccalib.so \
    opencv-4.1.0/lib/libopencv_ccalib.so.4.1 \
    opencv-4.1.0/lib/libopencv_ccalib.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_core.so \
    opencv-4.1.0/lib/libopencv_core.so.4.1 \
    opencv-4.1.0/lib/libopencv_core.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_datasets.so \
    opencv-4.1.0/lib/libopencv_datasets.so.4.1 \
    opencv-4.1.0/lib/libopencv_datasets.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_dnn.so \
    opencv-4.1.0/lib/libopencv_dnn.so.4.1 \
    opencv-4.1.0/lib/libopencv_dnn.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_dnn_objdetect.so \
    opencv-4.1.0/lib/libopencv_dnn_objdetect.so.4.1 \
    opencv-4.1.0/lib/libopencv_dnn_objdetect.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_dpm.so \
    opencv-4.1.0/lib/libopencv_dpm.so.4.1 \
    opencv-4.1.0/lib/libopencv_dpm.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_face.so \
    opencv-4.1.0/lib/libopencv_face.so.4.1 \
    opencv-4.1.0/lib/libopencv_face.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_features2d.so \
    opencv-4.1.0/lib/libopencv_features2d.so.4.1 \
    opencv-4.1.0/lib/libopencv_features2d.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_flann.so \
    opencv-4.1.0/lib/libopencv_flann.so.4.1 \
    opencv-4.1.0/lib/libopencv_flann.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_freetype.so \
    opencv-4.1.0/lib/libopencv_freetype.so.4.1 \
    opencv-4.1.0/lib/libopencv_freetype.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_fuzzy.so \
    opencv-4.1.0/lib/libopencv_fuzzy.so.4.1 \
    opencv-4.1.0/lib/libopencv_fuzzy.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_gapi.so \
    opencv-4.1.0/lib/libopencv_gapi.so.4.1 \
    opencv-4.1.0/lib/libopencv_gapi.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_hfs.so \
    opencv-4.1.0/lib/libopencv_hfs.so.4.1 \
    opencv-4.1.0/lib/libopencv_hfs.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_highgui.so \
    opencv-4.1.0/lib/libopencv_highgui.so.4.1 \
    opencv-4.1.0/lib/libopencv_highgui.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_img_hash.so \
    opencv-4.1.0/lib/libopencv_img_hash.so.4.1 \
    opencv-4.1.0/lib/libopencv_img_hash.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_imgcodecs.so \
    opencv-4.1.0/lib/libopencv_imgcodecs.so.4.1 \
    opencv-4.1.0/lib/libopencv_imgcodecs.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_imgproc.so \
    opencv-4.1.0/lib/libopencv_imgproc.so.4.1 \
    opencv-4.1.0/lib/libopencv_imgproc.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_line_descriptor.so \
    opencv-4.1.0/lib/libopencv_line_descriptor.so.4.1 \
    opencv-4.1.0/lib/libopencv_line_descriptor.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_ml.so \
    opencv-4.1.0/lib/libopencv_ml.so.4.1 \
    opencv-4.1.0/lib/libopencv_ml.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_objdetect.so \
    opencv-4.1.0/lib/libopencv_objdetect.so.4.1 \
    opencv-4.1.0/lib/libopencv_objdetect.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_optflow.so \
    opencv-4.1.0/lib/libopencv_optflow.so.4.1 \
    opencv-4.1.0/lib/libopencv_optflow.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_phase_unwrapping.so \
    opencv-4.1.0/lib/libopencv_phase_unwrapping.so.4.1 \
    opencv-4.1.0/lib/libopencv_phase_unwrapping.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_photo.so \
    opencv-4.1.0/lib/libopencv_photo.so.4.1 \
    opencv-4.1.0/lib/libopencv_photo.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_plot.so \
    opencv-4.1.0/lib/libopencv_plot.so.4.1 \
    opencv-4.1.0/lib/libopencv_plot.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_quality.so \
    opencv-4.1.0/lib/libopencv_quality.so.4.1 \
    opencv-4.1.0/lib/libopencv_quality.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_reg.so \
    opencv-4.1.0/lib/libopencv_reg.so.4.1 \
    opencv-4.1.0/lib/libopencv_reg.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_rgbd.so \
    opencv-4.1.0/lib/libopencv_rgbd.so.4.1 \
    opencv-4.1.0/lib/libopencv_rgbd.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_saliency.so \
    opencv-4.1.0/lib/libopencv_saliency.so.4.1 \
    opencv-4.1.0/lib/libopencv_saliency.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_shape.so \
    opencv-4.1.0/lib/libopencv_shape.so.4.1 \
    opencv-4.1.0/lib/libopencv_shape.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_stereo.so \
    opencv-4.1.0/lib/libopencv_stereo.so.4.1 \
    opencv-4.1.0/lib/libopencv_stereo.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_stitching.so \
    opencv-4.1.0/lib/libopencv_stitching.so.4.1 \
    opencv-4.1.0/lib/libopencv_stitching.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_structured_light.so \
    opencv-4.1.0/lib/libopencv_structured_light.so.4.1 \
    opencv-4.1.0/lib/libopencv_structured_light.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_superres.so \
    opencv-4.1.0/lib/libopencv_superres.so.4.1 \
    opencv-4.1.0/lib/libopencv_superres.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_surface_matching.so \
    opencv-4.1.0/lib/libopencv_surface_matching.so.4.1 \
    opencv-4.1.0/lib/libopencv_surface_matching.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_text.so \
    opencv-4.1.0/lib/libopencv_text.so.4.1 \
    opencv-4.1.0/lib/libopencv_text.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_tracking.so \
    opencv-4.1.0/lib/libopencv_tracking.so.4.1 \
    opencv-4.1.0/lib/libopencv_tracking.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_video.so \
    opencv-4.1.0/lib/libopencv_video.so.4.1 \
    opencv-4.1.0/lib/libopencv_video.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_videoio.so \
    opencv-4.1.0/lib/libopencv_videoio.so.4.1 \
    opencv-4.1.0/lib/libopencv_videoio.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_videostab.so \
    opencv-4.1.0/lib/libopencv_videostab.so.4.1 \
    opencv-4.1.0/lib/libopencv_videostab.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_xfeatures2d.so \
    opencv-4.1.0/lib/libopencv_xfeatures2d.so.4.1 \
    opencv-4.1.0/lib/libopencv_xfeatures2d.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_ximgproc.so \
    opencv-4.1.0/lib/libopencv_ximgproc.so.4.1 \
    opencv-4.1.0/lib/libopencv_ximgproc.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_xobjdetect.so \
    opencv-4.1.0/lib/libopencv_xobjdetect.so.4.1 \
    opencv-4.1.0/lib/libopencv_xobjdetect.so.4.1.0 \
    opencv-4.1.0/lib/libopencv_xphoto.so \
    opencv-4.1.0/lib/libopencv_xphoto.so.4.1 \
    opencv-4.1.0/lib/libopencv_xphoto.so.4.1.0 \
    opencv-4.1.0/lib/python2.7/dist-packages/cv2/__init__.py \
    opencv-4.1.0/lib/python2.7/dist-packages/cv2/config-2.7.py \
    opencv-4.1.0/lib/python2.7/dist-packages/cv2/config.py \
    opencv-4.1.0/lib/python2.7/dist-packages/cv2/load_config_py2.py \
    opencv-4.1.0/lib/python2.7/dist-packages/cv2/load_config_py3.py \
    opencv-4.1.0/lib/python2.7/dist-packages/cv2/python-2.7/cv2.so \
    opencv-4.1.0/lib/python3.7/dist-packages/cv2/__init__.py \
    opencv-4.1.0/lib/python3.7/dist-packages/cv2/config-3.7.py \
    opencv-4.1.0/lib/python3.7/dist-packages/cv2/config.py \
    opencv-4.1.0/lib/python3.7/dist-packages/cv2/load_config_py2.py \
    opencv-4.1.0/lib/python3.7/dist-packages/cv2/load_config_py3.py \
    opencv-4.1.0/lib/python3.7/dist-packages/cv2/python-3.7/cv2.cpython-37m-x86_64-linux-gnu.so \
    opencv-4.1.0/lib/python3.7/dist-packages/cv2/python-3.7/cv2.so \
    opencv-4.1.0/share/licenses/opencv4/SoftFloat-COPYING.txt \
    opencv-4.1.0/share/licenses/opencv4/ade-LICENSE \
    opencv-4.1.0/share/licenses/opencv4/jasper-LICENSE \
    opencv-4.1.0/share/licenses/opencv4/jasper-README \
    opencv-4.1.0/share/licenses/opencv4/jasper-copyright \
    opencv-4.1.0/share/licenses/opencv4/libjpeg-turbo-LICENSE.md \
    opencv-4.1.0/share/licenses/opencv4/libjpeg-turbo-README.ijg \
    opencv-4.1.0/share/licenses/opencv4/libjpeg-turbo-README.md \
    opencv-4.1.0/share/licenses/opencv4/libpng-LICENSE \
    opencv-4.1.0/share/licenses/opencv4/libpng-README \
    opencv-4.1.0/share/licenses/opencv4/libtiff-COPYRIGHT \
    opencv-4.1.0/share/licenses/opencv4/opencl-headers-LICENSE.txt \
    opencv-4.1.0/share/licenses/opencv4/openexr-AUTHORS.ilmbase \
    opencv-4.1.0/share/licenses/opencv4/openexr-AUTHORS.openexr \
    opencv-4.1.0/share/licenses/opencv4/openexr-LICENSE \
    opencv-4.1.0/share/licenses/opencv4/openexr-fix_msvc2013_errors.patch \
    opencv-4.1.0/share/licenses/opencv4/protobuf-LICENSE \
    opencv-4.1.0/share/licenses/opencv4/protobuf-README.md \
    opencv-4.1.0/share/licenses/opencv4/quirc-LICENSE \
    opencv-4.1.0/share/licenses/opencv4/zlib-README \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_eye.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_eye_tree_eyeglasses.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_frontalcatface.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_frontalcatface_extended.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_frontalface_alt.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_frontalface_alt2.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_frontalface_alt_tree.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_frontalface_default.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_fullbody.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_lefteye_2splits.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_licence_plate_rus_16stages.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_lowerbody.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_profileface.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_righteye_2splits.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_russian_plate_number.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_smile.xml \
    opencv-4.1.0/share/opencv4/haarcascades/haarcascade_upperbody.xml \
    opencv-4.1.0/share/opencv4/lbpcascades/lbpcascade_frontalcatface.xml \
    opencv-4.1.0/share/opencv4/lbpcascades/lbpcascade_frontalface.xml \
    opencv-4.1.0/share/opencv4/lbpcascades/lbpcascade_frontalface_improved.xml \
    opencv-4.1.0/share/opencv4/lbpcascades/lbpcascade_profileface.xml \
    opencv-4.1.0/share/opencv4/lbpcascades/lbpcascade_silverware.xml \
    opencv-4.1.0/share/opencv4/valgrind.supp \
    opencv-4.1.0/share/opencv4/valgrind_3rdparty.supp \
    other/GUI_en_GB.ts \
    resources/main.qml
